#!/usr/bin/env node
/**
 * Context Renderer Service
 * 
 * 基于 opencode_executor 的七个 slot 上下文渲染模块
 * - Slot 0: LEGAL_PREFIX - 法律前缀/免责声明
 * - Slot 1: BINDING_REFS - 绑定引用
 * - Slot 2: ROLE_CAPSULE - Role 胶囊
 * - Slot 3: TASK_BUNDLE - 任务包
 * - Slot 4: STATE - 状态
 * - Slot 5: TOOLS - 工具
 * - Slot 6: OPTIONAL_CONTEXT - 可选上下文
 */

import http from "node:http"
import url from "node:url"
import fs from "node:fs"
import path from "node:path"

const CONFIG = {
  PORT: process.env.CONTEXT_RENDERER_PORT || 18004,
  REPO_ROOT: process.env.REPO_ROOT || "/app/scc-bd"
}

// 日志
function log(level, message, meta = {}) {
  const timestamp = new Date().toISOString()
  console.log(`[${timestamp}] [${level.toUpperCase()}] ${message}`, meta)
}

/**
 * ==================== 七个 Slot 渲染器 ====================
 */

/**
 * Slot 0: LEGAL_PREFIX - 法律前缀/免责声明
 */
function renderLegalPrefix(params) {
  const { repoRoot, customPrefix } = params
  
  const text = customPrefix || `
# SCC Context Pack v1
This context pack is generated by SCC (Smart Code Collaboration) system.
All references are binding and version-controlled.
`.trim()

  return {
    slot: 0,
    kind: "LEGAL_PREFIX",
    text
  }
}

/**
 * Slot 1: BINDING_REFS - 绑定引用
 */
function renderBindingRefs(params) {
  const { repoRoot, role, mode, files = [] } = params
  
  const refs_index = {
    schema_version: "scc.refs_index.v1",
    repo_root: repoRoot,
    role: role || null,
    mode: mode || "execute",
    files: files.map(f => ({
      path: f,
      sha256: null // 可以计算实际 hash
    })),
    generated_at: new Date().toISOString()
  }
  
  return {
    slot: 1,
    kind: "BINDING_REFS",
    refs_index
  }
}

/**
 * Slot 2: ROLE_CAPSULE - Role 胶囊
 */
function renderRoleCapsule(params) {
  const { repoRoot, role, roleConfig = {} } = params
  
  const capsule = {
    schema_version: "scc.role_capsule.v1",
    role: role || "executor",
    system_prompt: roleConfig.systemPrompt || `You are a ${role} agent.`,
    capabilities: roleConfig.capabilities || [],
    constraints: roleConfig.constraints || [],
    skills: roleConfig.skills || [],
    model: roleConfig.model || "opencode/kimi-k2.5-free"
  }
  
  return {
    slot: 2,
    kind: "ROLE_CAPSULE",
    capsule
  }
}

/**
 * Slot 3: TASK_BUNDLE - 任务包
 */
function renderTaskBundle(params) {
  const { task } = params
  
  const bundle = {
    schema_version: "scc.task_bundle.v1",
    task: {
      id: task?.id || null,
      title: task?.title || "",
      goal: task?.goal || "",
      description: task?.description || "",
      role: task?.role || null,
      files: task?.files || [],
      context: task?.context || {}
    },
    generated_at: new Date().toISOString()
  }
  
  return {
    slot: 3,
    kind: "TASK_BUNDLE",
    bundle
  }
}

/**
 * Slot 4: STATE - 状态
 */
function renderState(params) {
  const { state = null } = params
  
  return {
    slot: 4,
    kind: "STATE",
    state
  }
}

/**
 * Slot 5: TOOLS - 工具
 */
function renderTools(params) {
  const { tools = null, executor = "oltcli" } = params
  
  const defaultTools = {
    executor,
    available: [
      "read_file",
      "write_file",
      "edit_file",
      "list_dir",
      "search_files",
      "grep_search",
      "run_command"
    ]
  }
  
  return {
    slot: 5,
    kind: "TOOLS",
    tools: tools || defaultTools
  }
}

/**
 * Slot 6: OPTIONAL_CONTEXT - 可选上下文
 */
function renderOptionalContext(params) {
  const { optionalContext = null, skills = [], contextPack = null } = params
  
  const context = optionalContext || {
    skills: skills.map(s => ({
      id: s.id || s,
      name: s.name || s
    })),
    context_pack: contextPack
  }
  
  return {
    slot: 6,
    kind: "OPTIONAL_CONTEXT",
    optional_context: context
  }
}

/**
 * 渲染完整上下文包（七个 slot）
 */
function renderContextPack(params) {
  const slots = [
    renderLegalPrefix(params),
    renderBindingRefs(params),
    renderRoleCapsule(params),
    renderTaskBundle(params),
    renderState(params),
    renderTools(params),
    renderOptionalContext(params)
  ]
  
  return {
    schema_version: "scc.context_pack.v1",
    created_at: new Date().toISOString(),
    slots
  }
}

/**
 * 渲染为文本格式
 */
function renderContextText(params) {
  const pack = renderContextPack(params)
  
  const lines = [
    `SCC Context Pack v1`,
    `created_at: ${pack.created_at}`,
    ``
  ]
  
  for (const slot of pack.slots) {
    lines.push(`SLOT${slot.slot} ${slot.kind}`)
    
    switch (slot.kind) {
      case "LEGAL_PREFIX":
        lines.push(String(slot.text ?? "").trimEnd())
        break
      case "BINDING_REFS":
        lines.push(JSON.stringify(slot.refs_index, null, 2))
        break
      case "ROLE_CAPSULE":
        lines.push(JSON.stringify(slot.capsule, null, 2))
        break
      case "TASK_BUNDLE":
        lines.push(JSON.stringify(slot.bundle, null, 2))
        break
      case "STATE":
        lines.push(slot.state ? JSON.stringify(slot.state, null, 2) : "null")
        break
      case "TOOLS":
        lines.push(slot.tools ? JSON.stringify(slot.tools, null, 2) : "null")
        break
      case "OPTIONAL_CONTEXT":
        lines.push(slot.optional_context ? JSON.stringify(slot.optional_context, null, 2) : "null")
        break
    }
    
    lines.push("")
  }
  
  return lines.join("\n")
}

/**
 * HTTP 请求处理
 */
async function handleRequest(req, res) {
  const parsedUrl = url.parse(req.url, true)
  const pathname = parsedUrl.pathname
  
  // CORS
  res.setHeader("Access-Control-Allow-Origin", "*")
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
  res.setHeader("Access-Control-Allow-Headers", "Content-Type")
  
  if (req.method === "OPTIONS") {
    res.writeHead(200)
    res.end()
    return
  }
  
  try {
    if (pathname === "/health") {
      res.writeHead(200, { "Content-Type": "application/json" })
      res.end(JSON.stringify({ status: "ok" }))
      return
    }
    
    if (pathname === "/render" && req.method === "POST") {
      let body = ""
      req.on("data", chunk => body += chunk)
      req.on("end", () => {
        try {
          const params = JSON.parse(body)
          const pack = renderContextPack(params)
          const text = renderContextText(params)
          
          res.writeHead(200, { "Content-Type": "application/json" })
          res.end(JSON.stringify({
            pack,
            text,
            slots_count: 7
          }))
        } catch (e) {
          res.writeHead(400)
          res.end(JSON.stringify({ error: e.message }))
        }
      })
      return
    }
    
    if (pathname === "/render/slot" && req.method === "POST") {
      let body = ""
      req.on("data", chunk => body += chunk)
      req.on("end", () => {
        try {
          const { slot, params } = JSON.parse(body)
          
          let result
          switch (slot) {
            case 0: result = renderLegalPrefix(params); break
            case 1: result = renderBindingRefs(params); break
            case 2: result = renderRoleCapsule(params); break
            case 3: result = renderTaskBundle(params); break
            case 4: result = renderState(params); break
            case 5: result = renderTools(params); break
            case 6: result = renderOptionalContext(params); break
            default:
              res.writeHead(400)
              res.end(JSON.stringify({ error: "Invalid slot number" }))
              return
          }
          
          res.writeHead(200, { "Content-Type": "application/json" })
          res.end(JSON.stringify(result))
        } catch (e) {
          res.writeHead(400)
          res.end(JSON.stringify({ error: e.message }))
        }
      })
      return
    }
    
    if (pathname === "/render/text" && req.method === "POST") {
      let body = ""
      req.on("data", chunk => body += chunk)
      req.on("end", () => {
        try {
          const params = JSON.parse(body)
          const text = renderContextText(params)
          
          res.writeHead(200, { "Content-Type": "text/plain" })
          res.end(text)
        } catch (e) {
          res.writeHead(400)
          res.end(JSON.stringify({ error: e.message }))
        }
      })
      return
    }
    
    res.writeHead(404)
    res.end(JSON.stringify({ error: "Not found" }))
  } catch (e) {
    log("error", "Request failed", { error: e.message })
    res.writeHead(500)
    res.end(JSON.stringify({ error: e.message }))
  }
}

/**
 * 启动服务
 */
function start() {
  const server = http.createServer(handleRequest)
  
  server.listen(CONFIG.PORT, () => {
    log("info", `Context Renderer Service started`, { port: CONFIG.PORT })
  })
  
  // 优雅退出
  process.on("SIGINT", () => {
    log("info", "Shutting down...")
    server.close(() => {
      process.exit(0)
    })
  })
}

start()
